name: Crunch into Single HTML

on: [workflow_dispatch]

jobs:
  build-single-file:
    runs-on: ubuntu-latest

    steps:
      - name: Grab the Game Code
        uses: actions/checkout@v4
        with:
          submodules: recursive # This grabs hidden extra files

      - name: Install the C++ to Web Translator
        uses: mymindstorm/setup-emsdk@v14

      - name: Install the Builder Bots
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip ninja-build
          pip3 install meson

      - name: CRUNCH THE MONSTER
        run: |
          # 1. Set the "Single File" magic flag
          export LDFLAGS="-s SINGLE_FILE=1"
          
          # 2. Find the missing map file automatically
          EMS_FILE=$(find . -name "emscripten.txt" | head -n 1)
          echo "Found the map at: $EMS_FILE"
          
          # 3. Build the game
          meson setup builddir --cross-file "$EMS_FILE"
          ninja -C builddir

      - name: Hand over the HTML File!
        uses: actions/upload-artifact@v4
        with:
          name: Playable-HTML-File
          path: builddir/*.html
